// index
export const USER_LOGIN = 'USER_LOGIN';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// app action
export const GET_HOME_PAGE_DATA = 'GET_HOME_PAGE_DATA';

// cart action
export const SUBMITTING_CART_DATA = 'SUBMITTING_CART_DATA';
export const SUBMITTING_CART_DATA_FINISHED = 'SUBMITTING_CART_DATA_FINISHED';
export const SYNC_CART_WHEN_LOGIN = 'SYNC_CART_WHEN_LOGIN';
export const SYNC_CART_TO_SERVER = 'SYNC_CART_TO_SERVER';
export const INCREASE_PRODUCT_QUANTITY_IN_CART = 'INCREASE_PRODUCT_QUANTITY_IN_CART';
export const DECREASE_PRODUCT_QUANTITY_IN_CART = 'DECREASE_PRODUCT_QUANTITY_IN_CART';
export const REMOVE_PRODUCT_IN_CART = 'REMOVE_PRODUCT_IN_CART';
export const CLEAR_CART_DATA = 'CLEAR_CART_DATA';

// Message action
export const ADD_PRODUCT_IN_DETAILS_PAGE = 'ADD_PRODUCT_IN_DETAILS_PAGE';
export const CLOSE_TOAST = 'CLOSE_TOAST';

// delivery addressAction
export const SAVE_DELIVERY_ADDRESS = 'SAVE_DELIVERY_ADDRESS';

// modal action
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const CONFIRM_REMOVE_PRODUCT_MODAL = 'CONFIRM_REMOVE_PRODUCT_MODAL';

export const SAVE_ADMIN_ROLES = 'SAVE_ADMIN_ROLES';